### ISSUE TITLE
Output broken when using 'date.handler'  => 'intl'

### ISSUE THREAD

**Issue by jamiehunterdesign** [bnomei/kirby3-recently-modified#3]
I'd like to use this in a multi-language setup, but it seems to be broken when using `'date.handler'  => 'intl'` in config. In English, the date and time looks like this: `2023/44/28 11::` . Changing the language in the panel sometimes just displays `false`.

**Comment by bnomei** [comment]
i will take a look asap

**Comment by bnomei** [comment]
the plugin writes the modified integer timestamp to a cache and uses that for filtering. but it  forwards the `$page->modified($format)` value to the field. so if you change the input you need to change the output `$format` as well. 

**site/config/config.php**
```php
<?php

return [
   'bnomei.recently-modified.format' => 'YOUR FORMAT HERE', // default: Y/m/d H:i:s
   // other options
];

```

**Comment by bnomei** [comment]
@jamiehunterdesign this seems to do the tricks. the formats are a bit different that the one from the `date()`

https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

```php
return [
    'debug' => true,
    'date.handler'  => 'intl',
    'bnomei.recently-modified.format' => 'Y/M/dd H:mm:ss',
];
```
